baseurl: "/"
languageCode: "en-us"
title: "Integrated Ethics Labs"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: "integrated-ethics"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Labs
      url: "labs/"
      weight: 3
    - name: Resources
      url: "resources/"
      weight: 4
    - name: Publications/Talks
      url: "pubs/"
      weight: 5
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    # - name: Tags
    #   url: "tags/"
    #   weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "Integrated Ethics Labs for teaching ethics in computing and data courses"
  # footer: "CC-BY-NC-SA-4.0"
  GithubEdit: "https://github.com/integrated-ethics/web/edit/main/content/"

markup:
  goldmark:
    renderer:
      unsafe: true
